[package]
name = "dumpling"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hmac-sha256 = "1.1.2"
md5 = "0.7.0"
sha1_smol = "1.0.0"
